### ISSUE TITLE
Ubuntu 20.04.3 after initial barrage of requests for few seconds, I get about 3 requests a second no matter the number of threads

### ISSUE THREAD

**Issue by vvkleban** [AlexTrushkovsky/NoWarDDoS#44]
I have tried 50 and 500 threads - doesn't matter. 100 Mbps reliable connection, 8 core with 16 GB of RAM - the requests seem to be bottlenecked somewhere else

**Comment by dariy-vel** [comment]
Does the process finish at all after that?

**Comment by dariy-vel** [comment]
Fixed
